import {CATALOG,WORKS,serviceTitle} from './core.js';
const reportEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reportDate=v=>v?v.split('-').reverse().join('/'):'—';
const reportEuro=v=>v===null?'Non indicato':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v);
export function reportData(db,{vehicleID='',from='',to=''}={}){
 for(const value of [from,to])if(value&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value))throw Error('Inserisci date valide.');
 if(from&&to&&from>to)throw Error('La data iniziale deve precedere quella finale.');
 const rows=db.services.filter(s=>(!vehicleID||s.vehicleID===vehicleID)&&(!from||s.date>=from)&&(!to||s.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt)).map(s=>({service:s,vehicle:db.vehicles.find(v=>v.id===s.vehicleID)}));
 if(!rows.length)throw Error('Nessun lavoro effettuato nel periodo selezionato.');
 return {rows,from,to,scope:vehicleID?db.vehicles.find(v=>v.id===vehicleID)?.plate:'Tutta l’officina',total:rows.reduce((sum,{service:s})=>sum+Math.round((s.cost??0)*100),0)/100,missing:rows.filter(({service:s})=>s.cost===null).length,cars:new Set(rows.map(({service:s})=>s.vehicleID)).size};
}
const reportColumns=['Targa','Marca / modello','Cliente','Data','Km','Lavori effettuati','Olio motore','Litri olio','Olio trasmissione','Ricambi / filtri','Note','Costo EUR','Prossimo controllo km','Prossimo controllo data','Prezzi per lavoro'];
const reportValues=({service:s,vehicle:v})=>[v.plate,[v.make,v.model].filter(Boolean).join(' '),v.owner,reportDate(s.date),s.kilometers,serviceTitle(s),s.engineOil,s.oilLiters,s.transmissionOil,s.parts,s.notes,s.cost===null?'':s.cost.toFixed(2).replace('.',','),s.nextKilometers??'',s.nextDate?reportDate(s.nextDate):'',Object.entries(s.workPrices??{}).map(([k,p])=>(CATALOG.find(w=>w[0]===k)?.[1]??WORKS.find(w=>w[0]===k)?.[1]??k)+': '+reportEuro(p)).join(' | ')];
export function reportCSV(r){
 const cell=value=>{let s=String(value??'');if(/^[\s]*[=+@-]|^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
 return '\uFEFF'+[reportColumns,...r.rows.map(reportValues)].map(row=>row.map(cell).join(';')).join('\r\n');
}
export function reportHTML(r){
 const e=reportEscape;
 const details=r.rows.map(({service:s,vehicle:v},i)=>`<article><h2>${i+1}. ${e(v.plate)} · ${reportDate(s.date)}</h2><p class="muted">${e([v.make,v.model].filter(Boolean).join(' '))} · Cliente: ${e(v.owner||'Non indicato')} · ${s.kilometers.toLocaleString('it-IT')} km</p><dl><dt>Lavori effettuati</dt><dd>${e(serviceTitle(s))}</dd>${[['Olio motore',s.engineOil],['Litri olio motore',s.oilLiters],['Olio trasmissione',s.transmissionOil],['Ricambi / filtri',s.parts],['Note',s.notes],['Costo',reportEuro(s.cost)],['Prossimo controllo',[(s.nextKilometers!==null?s.nextKilometers.toLocaleString('it-IT')+' km':''),s.nextDate?'entro il '+reportDate(s.nextDate):''].filter(Boolean).join(' · ')]].filter(([,value])=>value).map(([label,value])=>`<dt>${label}</dt><dd>${e(value)}</dd>`).join('')}</dl>${Object.keys(s.workPrices??{}).length?`<h3>Prezzi per lavoro</h3><dl>${Object.entries(s.workPrices).map(([k,p])=>`<dt>${e(CATALOG.find(w=>w[0]===k)?.[1]??WORKS.find(w=>w[0]===k)?.[1]??k)}</dt><dd>${reportEuro(p)}</dd>`).join('')}</dl>${s.works.length>Object.keys(s.workPrices).length?'<p class="muted">Totale parziale: alcune voci non hanno un prezzo.</p>':''}`:''}${s.photo?`<img class="vehicle-photo" src="${e(s.photo)}" alt="Foto del veicolo">`:''} </article>`).join('');
 // No scripts or external resources: the report can be read and printed offline.
 return `<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>Officina — Report lavori ${e(r.scope)}</title><style>.vehicle-photo{display:block;max-width:100%;max-height:360px;object-fit:contain;margin:16px 0}body{font:16px/1.5 system-ui,sans-serif;color:#182b35;background:#eef3f5;margin:0}main{max-width:900px;margin:28px auto;padding:32px;background:white}h1{font-size:30px;margin:0}h2{font-size:20px;margin:0}.brand{color:#197766;font-weight:750;letter-spacing:3px}.muted{color:#536571}.summary{display:flex;gap:24px;flex-wrap:wrap;background:#eef7f3;padding:18px;margin:24px 0}.summary strong{display:block;font-size:24px}article{border-top:1px solid #b8c7cd;padding:20px 0}dl{display:grid;grid-template-columns:170px 1fr;gap:7px 16px}dt{font-weight:650}dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.hint{padding:12px;border:1px solid #b8c7cd;font-size:14px}footer{font-size:13px;color:#536571}@media(max-width:600px){main{margin:0;padding:20px}dl{grid-template-columns:1fr;gap:4px}dd{margin-bottom:10px}}@media print{@page{size:A4;margin:15mm}body{background:white;font-size:11pt}main{margin:0;padding:0;max-width:none}.hint{display:none}h2,dt{break-after:avoid}dd{orphans:3;widows:3}article{break-inside:auto}.summary{background:white;border:1px solid #b8c7cd}}</style><main><p class="brand">OFFICINA</p><h1>Report dei lavori effettuati</h1><p>${e(r.scope)} · Periodo: ${r.from?reportDate(r.from):'dall’inizio'} — ${r.to?reportDate(r.to):'fino all’ultimo intervento'}</p><p class="hint">Per ottenere un PDF, apri il menu del browser → Stampa → Salva come PDF. Su iPhone puoi usare Condividi → Stampa e salvare il documento.</p><div class="summary"><div><strong>${r.rows.length}</strong>interventi</div><div><strong>${r.cars}</strong>auto</div><div><strong>${reportEuro(r.total)}</strong>totale costi registrati</div></div>${r.missing?`<p class="muted">${r.missing} interventi senza costo indicato, esclusi dal totale.</p>`:''}${details}<footer>Generato da Officina il ${new Date().toLocaleDateString('it-IT')}. I costi sono quelli inseriti nell’archivio; questo report non è una fattura.</footer></main></html>`;
}
