import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyDatabase,newID,normalizePlate,amount,integer,validateDatabase,validDate,sortedServices,currentKM,due,validateChronology,parseBackup,backupObject,demoDatabase} from '../core.js';
import {newSession,seal,unseal} from '../crypto.js';
const fixture=()=>demoDatabase();
test('targhe normalizzate e duplicati bloccati',()=>{assert.equal(normalizePlate('ab 123-cd'),'AB123CD');const d=fixture();d.vehicles.push({...d.vehicles[0],id:crypto.randomUUID(),plate:'demo-001'});assert.throws(()=>validateDatabase(d),/duplicate/);});
test('importi italiani senza ambiguità',()=>{assert.equal(amount('120,50'),120.5);assert.equal(amount('120.50'),120.5);assert.equal(amount(''),null);for(const s of ['-10','1.200,50','NaN','12,123','1e3','12x'])assert.throws(()=>amount(s));});
test('km interi e limite',()=>{assert.equal(integer('125000'),125000);for(const n of ['1.000','-1','10000000','1.5',''])assert.throws(()=>integer(n));});
test('date di calendario reali',()=>{assert.equal(validDate('2024-02-29'),true);for(const d of ['2026-02-29','2026-13-01','2026-04-31','xxx'])assert.equal(validDate(d),false);});
test('nessun intervento orfano o duplicato',()=>{const d=fixture();d.services[0].vehicleID=crypto.randomUUID();assert.throws(()=>validateDatabase(d),/associata/);const e=fixture();e.services.push(e.services[0]);assert.throws(()=>validateDatabase(e),/duplicati/);});
test('lavori, litri, costo e prossimo controllo validati',()=>{for(const patch of [{works:['unknown']},{works:[],otherWork:''},{oilLiters:'-1'},{cost:Infinity},{nextKilometers:10},{nextDate:'1999-01-01'},{kilometers:-1}]){const d=fixture();Object.assign(d.services[0],patch);assert.throws(()=>validateDatabase(d));}});
test('km attuali sono il massimo della scheda e degli interventi',()=>{const d=fixture();d.services[0].kilometers=90000;assert.equal(currentKM(d,d.vehicles[0]),90000);});
test('scadenza per km oppure data',()=>{const d=fixture();assert.equal(due(d,d.vehicles[0]),false);d.vehicles[0].kilometers=100000;assert.equal(due(d,d.vehicles[0]),true);d.vehicles[0].kilometers=85000;d.services[0].nextDate=d.services[0].date;assert.equal(due(d,d.vehicles[0]),true);});
test('ultimo intervento senza scadenza non recupera scadenze vecchie',()=>{const d=fixture();const old=d.services[0];old.date='2025-01-01';old.nextDate='2025-02-01';d.services.push({...old,id:crypto.randomUUID(),date:'2026-01-01',nextDate:null,nextKilometers:null});assert.equal(sortedServices(d,d.vehicles[0].id)[0].date,'2026-01-01');assert.equal(due(d,d.vehicles[0]),false);});
test('chilometraggio storico coerente',()=>{const d=fixture();d.services[0].date='2026-02-01';assert.throws(()=>validateChronology(d,{...d.services[0],id:crypto.randomUUID(),date:'2026-01-01',kilometers:90000}));assert.doesNotThrow(()=>validateChronology(d,{...d.services[0],id:crypto.randomUUID(),date:'2026-01-01',kilometers:80000}));});
test('backup roundtrip e archivio vuoto',()=>{const d=validateDatabase(fixture());assert.deepEqual(parseBackup(JSON.stringify(backupObject(d))),d);assert.deepEqual(parseBackup(JSON.stringify(emptyDatabase())),emptyDatabase());assert.throws(()=>parseBackup('{invalid}'));});
test('importazione dalla versione SwiftUI iOS',()=>{const d=fixture();d.services[0].works=['Olio motore','Filtro olio'];d.services[0].date='2026-01-01T08:00:00Z';delete d.services[0].nextDate;const result=parseBackup(JSON.stringify(d));assert.deepEqual(result.services[0].works,['engineOil','oilFilter']);assert.equal(result.services[0].date,'2026-01-01');assert.equal(result.services[0].nextDate,null);});
test('campi sconosciuti non entrano nell’archivio',()=>{const d=fixture();d.vehicles[0].extra={danger:true};assert.equal(validateDatabase(d).vehicles[0].extra,undefined);});
test('AES-GCM: roundtrip, password errata, manomissione e IV differenti',async()=>{const d=fixture(),session=await newSession('Password-di-test-2026');const a=await seal(d,session),b=await seal(d,session);assert.notEqual(a.iv,b.iv);assert.deepEqual((await unseal(a,'Password-di-test-2026')).value,d);await assert.rejects(unseal(a,'Password-errata-2026'));const raw=structuredClone(a);raw.data=(raw.data[0]==='A'?'B':'A')+raw.data.slice(1);await assert.rejects(unseal(raw,'Password-di-test-2026'));});
test('backup cifrato separato dal vault, limiti password e KDF',async()=>{await assert.rejects(newSession('corta'));const session=await newSession('Password-di-test-2026'),raw=await seal(backupObject(fixture()),session,'backup');await assert.rejects(unseal(raw,'Password-di-test-2026','vault'));raw.iterations=1;await assert.rejects(unseal(raw,'Password-di-test-2026','backup'));});

test("identificativi su HTTP senza randomUUID",()=>{const original=crypto.randomUUID;try{crypto.randomUUID=undefined;assert.match(newID(),/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);}finally{crypto.randomUUID=original;}});

test('promemoria auto: migrazione, backup e validazione',()=>{const d=fixture();const legacy=validateDatabase(d);assert.deepEqual(legacy.vehicles[0].plannedWorks,[]);assert.equal(legacy.vehicles[0].plannedOther,'');d.vehicles[0].plannedWorks=['engineOil','frontBrakes'];d.vehicles[0].plannedOther='Controllare perdita';const valid=validateDatabase(d);assert.deepEqual(parseBackup(JSON.stringify(backupObject(valid))),valid);for(const patch of [{plannedWorks:['unknown']},{plannedWorks:['engineOil','engineOil']},{plannedOther:12}]){const invalid=structuredClone(d);Object.assign(invalid.vehicles[0],patch);assert.throws(()=>validateDatabase(invalid));}});
